### ISSUE TITLE
Problem with OPTION EXPLICIT and procedure parameter

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#575]
I made a program with OPTION EXPLICIT ON
I made a procedure  : PROCEDURE tir [tankNumber]

tank number is declared as a global variable at the program's beginning with default type.

When I compile it I got : 
![image](https://user-images.githubusercontent.com/118670680/222965072-17bd943c-32b4-467f-a45e-8cb9d07c050e.png)

My workaround is to put OPTION EXPLICIT OFF before the procedure, but that reduces the interests of OPTION EXPLICIT.

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector, and **thank you for this bug report!**

The type of function parameters can be specified with the `AS` keyword. If missed, the default type will be used. I.e.

     PROCEDURE test[ a AS INTEGER, b AS BYTE]

The problem was that, due to a bug, the parameters of the procedures were not defined directly but the compiler tried to see if the variable had already been defined previously. And this gave the problem in the case of `OPTION EXPLICIT ON`.

The problem has been fixed on COLDFIX v1.13 [rev. 20230305.2311].

**Comment by ldir-hector** [comment]
Well I updated my compiler and saved but I still have a compilation problem :

![image](https://user-images.githubusercontent.com/118670680/223192300-4fddc2f6-6831-4849-866c-20ae907c73c8.png)

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector, and thank you again!

The problem was the same but with the pseudo parameter `_PARAM.

The problem has been fixed on COLDFIX v1.13 [rev. 20230306.2314].
