### ISSUE TITLE
Procedure can't return negative values

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#578]
The following code shall print Sinus direct = -7071 
```
BITMAP ENABLE(640,200,2)
CLS
GLOBAL monCosinus

DIM monCosinus AS SIGNED 32BIT(90) = #{9998,9994,9986,9976,9962,9945,9925,9903,9877,9848,9816,9781,9744,9703,9659,9613,9563,9511,9455,9397,9336,9272,9205,9135,9063,8988,8910,8829,8746,8660,8572,8480,8387,8290,8192,8090,7986,7880,7771,7660,7547,7431,7314,7193,7071,6947,6820,6691,6561,6428,6293,6157,6018,5878,5736,5592,5446,5299,5150,5000,4848,4695,4540,4384,4226,4067,3907,3746,3584,3420,3256,3090,2924,2756,2588,2419,2250,2079,1908,1736,1564,1392,1219,1045,872,698,523,349,175,0}


PROCEDURE cosinus[angle AS INTEGER]
	'Algo :
	'Si 0 => 10000
	'Si de 1 ? 90 => Retour tableau
	'Si de 91 ? 180 => faire tableau de 180 - angle
	'Si de -90 ? -1 => Faire tableau de ABS(angle)
	VAR tempAngle AS INTEGER, valeur AS SIGNED 32BIT
	tempAngle = -1
	PRINT "Angle param ";angle
	IF angle = 0 THEN 
		RETURN 10000
	ENDIF
	PRINT "TRACE 1"
	IF (angle > 0) AND (angle < 90)  THEN
		PRINT "TRACE 1.1" 
		RETURN monCosinus(angle-1)
	ENDIF
	PRINT "TRACE 2"
	IF (angle > 90) AND (angle <= 180) THEN 
		tempAngle = 180 - angle
		PRINT "tempAngle = ";tempAngle
		valeur = monCosinus(tempAngle-1)
		PRINT  "monCosinus(tempAngle-1)=";valeur
		RETURN valeur
	ENDIF
	PRINT "TRACE 3"
	IF (angle >= -90) AND (angle < 0) THEN 
		RETURN monCosinus(ABS(angle+1))
	ENDIF
	PRINT "TRACE 4"
	RETURN 0
END PROC

PROCEDURE sinus[angle AS INTEGER]
'Algo : sinus(Angle) = -cosinus(angle - 90)
	
	RETURN  -1 * cosinus[angle - 90]
END PROC

angle = 45
PRINT cosinus[angle] / 2000
valeur =sinus[angle] 
PRINT "Sinus direct = ";valeur
PRINT valeur / 2000
```

instead it displays : 58465
If I remove the -1 * before the cosinus call, it displays 7071 as expected. So it's a problem with negative values.

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and **thank you for your bug reporting!**

The real problem was not the sign, but the fact that, due to a mistake, the barrier between local and global variables was not as clear-cut as it seemed at first sight. The need to reserve memory for local variables meant that, by mistake, they could often not be considered local -- especially if returned as a return value.

The bug has been fixed with COLDFIX v1.13 [rev. 20230314.2213]

**Comment by ldir-hector** [comment]
Hello,

I still encounter this problem even after updating ugBasic yesterday !
Here is my new sample code : 

```
BITMAP ENABLE (160,200,16)
CLS

PROCEDURE negatif[angle AS INTEGER]
	RETURN angle * -1
END PROC

VAR angleGlobal AS INTEGER
angleGlobal = 135
PRINT negatif[angleGlobal]
PRINT negatif[135]
```
and the result : 
![image](https://user-images.githubusercontent.com/118670680/229279254-b7e12a09-5874-4d45-8cd0-462cb0af671e.png)

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector and **thank you for your bug report!**

I reopen the issue to investigate futher.

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector, the problem has been fixed on COLDFIX v1.13.1 [rev. 20230401.1701].
